# -*- coding: utf-8 -*-
"""ejercicio6_kernel2d.cu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9JKxdoR-YFalWwaU4jAhCPgsiZaZ0EK
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ejercicio6_kernel2d.cu
# #include <stdio.h>
# #include <cuda_runtime.h>
# 
# #define FILAS 4
# #define COLS 5
# 
# // Kernel 2D: cada hilo procesa una celda de la matriz
# __global__ void inicializarMatriz(int *d_mat, int filas, int cols) {
#   // Calcular índice de fila y columna para este hilo
#   int col = threadIdx.x + (blockIdx.x * blockDim.x);
#   int fila = threadIdx.y + (blockIdx.y * blockDim.y);
# 
#   // Guard: verificar límites
#   if (fila < filas && col < cols) {
#     // Convertir índice 2D a índice lineal 1D
#     int idx = fila * cols + col;
#     d_mat[idx] = fila + col;
#   }
# }
# 
# int main() {
#   int h_mat[FILAS * COLS];
#   int *d_mat;
#   cudaMalloc((void**)&d_mat, FILAS * COLS * sizeof(int));
# 
#   // Configurar bloques e hilos 2D
#   // dim3 permite definir dimensiones en 2D o 3D
#   dim3 hilosPorBloque(16, 16);  // block de 16x16 hilos
#   dim3 numBloques((COLS + hilosPorBloque.x - 1) / hilosPorBloque.x, (FILAS + hilosPorBloque.y - 1) / hilosPorBloque.y);
# 
#   inicializarMatriz<<<numBloques, hilosPorBloque>>>(d_mat, FILAS, COLS);
#   cudaDeviceSynchronize();
# 
#   cudaMemcpy(h_mat, d_mat, FILAS * COLS * sizeof(int), cudaMemcpyDeviceToHost);
# 
#   printf("Matriz inicializada por la GPU:\n");
#   for (int i = 0; i < FILAS; i++) {
#     for (int j = 0; j < COLS; j++) {
#       printf("%3d ", h_mat[i * COLS + j]);
#     }
#     printf("\n");
#   }
# 
#   cudaFree(d_mat);
#   return 0;
# }

!nvcc ejercicio6_kernel2d.cu -o ejercicio6 -arch=sm_75

!./ejercicio6

!./ejercicio6

!./ejercicio6