# -*- coding: utf-8 -*-
"""ejercicio5_cuadrado.cu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19C0mg-pQYJCEe76j8RofMoA6WPV0En4r
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ejercicio5_cuadrado.cu
# #include <stdio.h>
# #include <cuda_runtime.h>
# 
# #define N 20
# 
# // Kernel: eleva al cuadrado cada elemento del arreglo
# __global__ void cuadradoInPlace(int *d_datos, int n) {
#   int idx = threadIdx.x + (blockIdx.x * blockDim.x) ;
#   if (idx < n) {
#     d_datos[idx] = d_datos[idx] * d_datos[idx];
#   }
# }
# 
# int main() {
#   int h_datos[N];
#   for (int i = 0; i < N; i++) h_datos[i] = i + 1; // [1, 2, ..., 20]
# 
#   printf("Datos originales:\n");
#   for (int i = 0; i < N; i++) printf("%4d", h_datos[i]);
#   printf("\n");
# 
#   int *d_datos;
#   cudaMalloc((void**)&d_datos, N * sizeof(int));
#   cudaMemcpy(d_datos, h_datos, N * sizeof(int), cudaMemcpyHostToDevice);
# 
#   cuadradoInPlace<<<1, N>>>(d_datos, N);
#   cudaDeviceSynchronize();
# 
#   cudaMemcpy(h_datos, d_datos, N * sizeof(int), cudaMemcpyDeviceToHost);
# 
#   printf("Despues de elevar al cuadrado en GPU:\n");
#   for (int i = 0; i < N; i++) printf("%4d", h_datos[i]);
#   printf("\n");
# 
#   int ok = 1;
#   for (int i = 0; i < N; i++) {
#     if (h_datos[i] != (i + 1) * (i + 1)) {
#       ok = 0;
#       break;
#     }
#   }
#   if (ok) printf("Todos los elementos son correctos\n");
# 
# 
#   cudaFree(d_datos);
#   return 0;
# }

!nvcc ejercicio5_cuadrado.cu -o ejercicio5 -arch=sm_75

!./ejercicio5